### ISSUE TITLE
Missing Content Security Policy (CSP)

### ISSUE THREAD

**Issue by dliptai** [ADACS-Australia/starfit-server#1]
"The Monash University Cyber Risk and Resilience Team has reported that your instance hosting a site is missing Content Security Policy (CSP). The Content Security Policy provides a valuable safety net that protects your website from malicious cross-site scripting (XSS) attacks. A well configured policy will stop an attacker attempting to inject their code, or references to other malicious content, into the website.

Recommendation:
Enable CSP headers via your webserver configuration. This link [https://infosec.mozilla.org/guidelines/web_security.html#content-security-policy](https://protect-au.mimecast.com/s/ZmXGCYWLoWCVjAmzh9G0J5?domain=infosec.mozilla.org) provides some examples on csp headers to use."

**Comment by conradtchan** [comment]
Resolved in ad61e23abd6fe010f6e9e560cb20d5d2491a4b46
