### ISSUE TITLE
svg plots are not shown on web page

### ISSUE THREAD

**Issue by 2sn** [ADACS-Australia/starfit-server#12]
When selecting `svg` output, they don't show up on the web page.  

It could be a we browser issue?  On Linux/Google-Chrome they are just skipped, on Firefox a black square results.  Same on WinX/Edge, Chrome - skipped.

**Comment by dliptai** [comment]
It's because of the CSP
```
Refused to frame '' because it violates the following Content Security Policy directive: "default-src https:". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```
