### ISSUE TITLE
back button stuck

### ISSUE THREAD

**Issue by dliptai** [ADACS-Australia/starfit-server#2]
(linking from https://github.com/conradtchan/starfit/issues/25)

"when I press the "back" button on the results page the web page seems to get stuck"

**Comment by dliptai** [comment]
I think apache just needs to be configured to tell browsers to not cache the home page https://httpd.apache.org/docs/2.0/mod/mod_expires.html

**Comment by 2sn** [comment]
The back button no longer crashes, but does not get you back to the form where you left off, e.g., the same tab and input data.

**Comment by 2sn** [comment]
E.g., try with GA.  (also, if you chose the HW 2002 the code actually crashes)

**Comment by 2sn** [comment]
@dliptai @conradtchan I think this is something where your help might be most urgent at this time.

**Comment by conradtchan** [comment]
I just attempted a fix in faacad4b19f37e408d0c309383302c5247efe101

Can you please give starfit.org a try?

**Comment by conradtchan** [comment]
I couldn't deploy to starfit.xyz. I think it's something wrong with my local DNS server because it loads fine on my phone.

**Comment by dliptai** [comment]
Works for me

**Comment by dliptai** [comment]
Reopening, as it is still an issue on Firefox

**Comment by 2sn** [comment]
@dliptai yes, I just had that feedback today from a colleague.

**Comment by 2sn** [comment]
User writes:
```
However my browser gets stuck when I want to return to the menu page after 
having processed the data once and would like to change the values of the input 
parameters.

> Did you use starfit.org or starfit.xyz (current)?

https://starfit.xyz/   This is the link you sent me.

> What browser / OS are you using?

Firefox on Linux. I have the same issue on my laptop with firefox and ubuntu.
```

**Comment by 2sn** [comment]
@conradtchan Thanks!  I will try this out later today with deployment to starfit.xyz (if not already done).

**Comment by conradtchan** [comment]
@2sn already deployed 😊

**Comment by 2sn** [comment]
@conradtchan Thanks!
