### ISSUE TITLE
info links are not created on deploy

### ISSUE THREAD

**Issue by 2sn** [ADACS-Australia/starfit-server#30]
see comments on #20

**Comment by dliptai** [comment]
It's because of https://github.com/ADACS-Australia/starfit-server/pull/22
starfit role got split into two separate roles, one for the python package, one for the webpage
should be fixed in 425570600a15f4c55a26c62c1f227fbd3defefcf

**Comment by 2sn** [comment]
@dliptai I had tried all different playbooks, none had worked.
