### ISSUE TITLE
python update instructions question

### ISSUE THREAD

**Issue by 2sn** [ADACS-Australia/starfit-server#4]
@david does one need to run the deploy script to just update the starfit package form PyPI, or would it be sufficient to run a `pip install -U` on the server?

**Comment by conradtchan** [comment]
Yep, it's fine to just do `pip install -U ` if the starfit python package is the only thing that's changed. The [ansible script](https://github.com/ADACS-Australia/starfit-server/blob/master/roles/starfit/tasks/main.yml) does the same thing.

P.S. I think you've tagged the wrong David. You're looking for @dliptai 🙂
